DELETE FROM `movies`;
INSERT INTO `movies` (`uid`, `title`, `year`) values ('TM1', 'The Matrix', 1999);
INSERT INTO `movies` (`uid`, `title`, `year`) values ('TM2', 'The Matrix Reloaded', 2003);
INSERT INTO `movies` (`uid`, `title`, `year`) values ('TM3', 'The Matrix Revolutions', 2003);

DELETE FROM `characters`;
INSERT INTO `characters` (`uid`, `name`) values ('TA', 'Thomas Anderson');
INSERT INTO `characters` (`uid`, `name`) values ('M', 'Morpheus');
INSERT INTO `characters` (`uid`, `name`) values ('T', 'Trinity');
INSERT INTO `characters` (`uid`, `name`) values ('AS', 'Agent Smith');
INSERT INTO `characters` (`uid`, `name`) values ('TO', 'The Oracle');
INSERT INTO `characters` (`uid`, `name`) values ('TM', 'The Merovingian');
INSERT INTO `characters` (`uid`, `name`) values ('P', 'Persephone');
INSERT INTO `characters` (`uid`, `name`) values ('TKM', 'The Keymaker');
INSERT INTO `characters` (`uid`, `name`) values ('TAR', 'The Architect');
INSERT INTO `characters` (`uid`, `name`) values ('S', 'Sati');

DELETE FROM `actors`;
INSERT INTO `actors` (`uid`, `name`) values ('KR', 'Keanu Reeves');
INSERT INTO `actors` (`uid`, `name`) values ('LF', 'Laurence Fishburne');
INSERT INTO `actors` (`uid`, `name`) values ('CAM', 'Carrie-Anne Moss');
INSERT INTO `actors` (`uid`, `name`) values ('HW', 'Hugo Weaving');
INSERT INTO `actors` (`uid`, `name`) values ('MA', 'Mary Alice');
INSERT INTO `actors` (`uid`, `name`) values ('LW', 'Lambert Wilson');
INSERT INTO `actors` (`uid`, `name`) values ('MB', 'Monica Bellucci');
INSERT INTO `actors` (`uid`, `name`) values ('RDK', 'Randall Duk Kim');
INSERT INTO `actors` (`uid`, `name`) values ('HB', 'Helmut Bakaitis');
INSERT INTO `actors` (`uid`, `name`) values ('TKA', 'Tanveer K. Atwai');

DELETE FROM `actings`;
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('KR', 'TM1', 'TA');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('KR', 'TM2', 'TA');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('KR', 'TM3', 'TA');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('LF', 'TM1', 'M');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('LF', 'TM2', 'M');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('LF', 'TM3', 'M');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('CAM', 'TM1', 'T');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('CAM', 'TM2', 'T');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('CAM', 'TM3', 'T');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('HW', 'TM1', 'AS');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('HW', 'TM2', 'AS');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('HW', 'TM3', 'AS');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('MA', 'TM1', 'TO');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('MA', 'TM2', 'TO');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('LW', 'TM2', 'TM');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('LW', 'TM3', 'TM');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('MB', 'TM2', 'P');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('MB', 'TM3', 'P');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('RDK', 'TM2', 'TKM');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('HB', 'TM2', 'TAR');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('HB', 'TM3', 'TAR');
INSERT INTO `actings` (`actor_uid`, `movie_uid`, `character_uid`) VALUES ('TKA', 'TM3', 'S');